# Generated by Django 5.0.7 on 2025-01-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='process_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
