# Generated by Django 5.0.7 on 2024-11-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedfolder',
            name='meeting_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
